INSERT INTO publisher (name) VALUES ('Penguin');
INSERT INTO publisher (name) VALUES ('Random House');
INSERT INTO publisher (name) VALUES ('Bloomsbury Publishing');
INSERT INTO publisher (name) VALUES ('Hatchette Book Group');
INSERT INTO publisher (name) VALUES ('Harper Collins');
INSERT INTO publisher (name) VALUES ('Simon and Schuster');
INSERT INTO publisher (name) VALUES ('Macmillan');
INSERT INTO publisher (name) VALUES ('Oxford University Press');
INSERT INTO publisher (name) VALUES ('Cambridge University Press');
INSERT INTO publisher (name) VALUES ('Edinburgh University Press');
INSERT INTO publisher (name) VALUES ('Melbourne University Press');
INSERT INTO publisher (name) VALUES ('The University of Chicago Press');
INSERT INTO publisher (name) VALUES ('Stanford University Press');
INSERT INTO publisher (name) VALUES ('MIT Press');
INSERT INTO publisher (name) VALUES ('Harvill Secker');
INSERT INTO publisher (name) VALUES ('Sphere Books');
INSERT INTO publisher (name) VALUES ('Little, Brown Book Group');
INSERT INTO publisher (name) VALUES ('Scholastic');
INSERT INTO publisher (name) VALUES ('Vintage books');
