INSERT INTO author (about, full_name) VALUES ('Cosmologist', 'Stephen Hawking');
INSERT INTO author (about, full_name) VALUES (NULL, 'Amor Towles');
INSERT INTO author (about, full_name) VALUES (NULL, 'Dan Brown');
INSERT INTO author (about, full_name) VALUES ('Pseudonym for J.K. Rowling', 'Robert Galbraith');
INSERT INTO author (about, full_name) VALUES (NULL, 'Neil Gaiman');
INSERT INTO author (about, full_name) VALUES ('Experimental psychologist at Harvard', 'Steven Pinker');
INSERT INTO author (about, full_name) VALUES (NULL, 'Terry Pratchett');
INSERT INTO author (about, full_name) VALUES ('Author of the bestselling Harry Potter books', 'J.K. Rowling');
INSERT INTO author (about, full_name) VALUES ('Historian', 'Yuval Noah Harari');
INSERT INTO author (about, full_name) VALUES (NULL, 'Philip Pullman');
INSERT INTO author (about, full_name) VALUES ('MIT professor', 'Max Tegmark');
INSERT INTO author (about, full_name) VALUES (NULL, 'Carlo Rovelli');
INSERT INTO author (about, full_name) VALUES (NULL, 'Khaled Hosseini');
INSERT INTO author (about, full_name) VALUES (NULL, 'Carlo Collodi');
INSERT INTO author (about, full_name) VALUES ('British evolutionary biologist at Oxford', 'Richard Dawkins');
INSERT INTO author (about, full_name) VALUES ('Greek philosopher that was a pupil of Socrates', 'Plato');
INSERT INTO author (about, full_name) VALUES ('Renown sleep scientist at Harvard', 'Matthew Walker');
INSERT INTO author (about, full_name) VALUES ('Novelist', 'Susanna Clarke');
INSERT INTO author (about, full_name) VALUES ('Novelist, short story writer, essayist and critic', 'Hilary Mantel');

