ALTER TABLE cover
DROP COLUMN IF EXISTS small_file_type;

ALTER TABLE cover
DROP COLUMN IF EXISTS medium_file_type;

ALTER TABLE cover
DROP COLUMN IF EXISTS large_file_type;

ALTER TABLE cover
DROP COLUMN IF EXISTS book;

ALTER TABLE cover
ADD COLUMN IF NOT EXISTS small_url VARCHAR;

ALTER TABLE cover
ADD COLUMN IF NOT EXISTS medium_url VARCHAR;

ALTER TABLE cover
ADD COLUMN IF NOT EXISTS large_url VARCHAR;
